import { expect, test, type Page } from '@playwright/test'
const password = process.env.E2E_PASSWORD || 'demo-password-123'
async function login(page: Page, name = 'owner') {
  await page.goto('/login')
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill(name + '@demo.example')
  await page.getByLabel(/^Password/).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Companies', exact: true })).toBeVisible()
}
async function select(page: Page, label: string, value: string) {
  await page.getByRole('combobox', { name: label, exact: true }).click()
  await page.getByRole('option', { name: value, exact: true }).click()
}
async function save(page: Page) {
  await page.getByRole('dialog').getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
}
test('live company lifecycle, assignments, access, ownership, roles and mobile layout', async ({
  page,
}) => {
  test.setTimeout(180_000)
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await login(page)
  const name = 'Browser QA ' + Date.now()
  let companyUrl = ''
  try {
    await page.getByRole('button', { name: 'Create company' }).click()
    await page.getByLabel('Company name').fill(name)
    await page.getByLabel('Description', { exact: true }).fill('Browser-verified workspace')
    await save(page)
    await page.getByRole('link', { name: 'Open ' + name, exact: true }).click()
    companyUrl = page.url()
    await page.reload()
    await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Edit company' }).click()
    await page.getByLabel('Website').fill('https://example.com')
    await save(page)
    await expect(page.getByRole('link', { name: 'https://example.com/' })).toBeVisible()
    await page.getByRole('tab', { name: 'Employees' }).click()
    await page.getByRole('button', { name: 'Add employee' }).click()
    await page.getByLabel('Full name').fill('QA Employee')
    await page.getByLabel('Work email').fill('qa@example.com')
    await page.getByLabel('Start date').fill('2026-01-01')
    await save(page)
    await page.getByRole('button', { name: 'Edit QA Employee', exact: true }).click()
    await page.getByLabel('Job title').fill('Engineer')
    await save(page)
    await expect(page.getByText('Engineer', { exact: true })).toBeVisible()
    await select(page, 'Employment status', 'leave')
    await expect(page.getByText('No records here yet.', { exact: false })).toBeVisible()
    await select(page, 'Employment status', 'All')
    await page.getByRole('tab', { name: 'Projects' }).click()
    await page.getByRole('button', { name: 'Create project' }).click()
    await page.getByLabel('Project name').fill('QA Project')
    await save(page)
    await page.getByRole('button', { name: 'Edit QA Project', exact: true }).click()
    await select(page, 'Status', 'active')
    await save(page)
    await page.getByRole('link', { name: 'View project' }).click()
    await page.getByRole('button', { name: 'Assign employee', exact: true }).click()
    await page.getByRole('button', { name: 'Assign', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.getByText('QA Employee', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Remove', exact: true }).click()
    await page.getByRole('button', { name: 'Confirm' }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.getByText('QA Employee', { exact: true })).toHaveCount(0)
    await page.getByRole('tab', { name: 'Access', exact: true }).click()
    await page.getByRole('button', { name: 'Grant access' }).click()
    await page.getByLabel('User UUID').fill('d0000000-0000-4000-8000-000000000003')
    await save(page)
    await page.getByRole('button', { name: 'Change role' }).click()
    await select(page, 'Role', 'admin')
    await save(page)
    await page.getByRole('button', { name: 'Sign out' }).click()
    await login(page, 'viewer')
    await page.goto(companyUrl)
    await expect(page.getByRole('button', { name: 'Edit company' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Delete company' })).toHaveCount(0)
    await expect(page.getByRole('tab', { name: 'Access' })).toHaveCount(0)
    await page.getByRole('button', { name: 'Sign out' }).click()
    await login(page)
    await page.goto(companyUrl + '/access')
    await page.getByRole('button', { name: 'Change role' }).click()
    await select(page, 'Role', 'viewer')
    await save(page)
    await page.getByRole('button', { name: 'Sign out' }).click()
    await login(page, 'viewer')
    await page.goto(companyUrl)
    await expect(page.getByRole('button', { name: 'Edit company' })).toHaveCount(0)
    await page.getByRole('tab', { name: 'Employees' }).click()
    await expect(page.getByRole('heading', { name: 'QA Employee' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Add employee' })).toHaveCount(0)
    await page.setViewportSize({ width: 375, height: 812 })
    await expect
      .poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth))
      .toBe(true)
    await page.screenshot({ path: 'test-results/mobile-employees.png', fullPage: true })
    await page.setViewportSize({ width: 1280, height: 900 })
    await page.getByRole('button', { name: 'Sign out' }).click()
    await login(page)
    await page.goto(companyUrl + '/access')
    await page.getByRole('button', { name: 'Transfer ownership' }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Transfer ownership' }).click()
    await expect(page.getByRole('tab', { name: 'Access' })).toHaveCount(0)
    await page.getByRole('button', { name: 'Sign out' }).click()
    await login(page, 'viewer')
    await page.goto(companyUrl + '/access')
    await page.getByRole('button', { name: 'Transfer ownership' }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Transfer ownership' }).click()
    await expect(page.getByRole('tab', { name: 'Access' })).toHaveCount(0)
    await page.getByRole('button', { name: 'Sign out' }).click()
    await login(page)
    await page.goto(companyUrl + '/access')
    await page.getByRole('button', { name: 'Revoke access' }).click()
    await page.getByRole('button', { name: 'Confirm' }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.getByRole('heading', { name: 'Viewer', exact: true })).toHaveCount(0)
    await page.getByRole('tab', { name: 'Employees' }).click()
    await page.getByRole('button', { name: 'Delete QA Employee', exact: true }).click()
    await page.getByRole('button', { name: 'Confirm' }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await page.getByRole('tab', { name: 'Projects' }).click()
    await page.getByRole('button', { name: 'Delete QA Project', exact: true }).click()
    await page.getByRole('button', { name: 'Confirm' }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await page.getByRole('tab', { name: 'Overview' }).click()
    await page.getByRole('button', { name: 'Delete company' }).click()
    await page.getByRole('button', { name: 'Confirm' }).click()
    await expect(page.getByRole('heading', { name: 'Companies', exact: true })).toBeVisible()
    companyUrl = ''
    expect(errors).toEqual([])
  } finally {
    if (companyUrl) {
      const csrf = await page.request.get('http://localhost:8080/api/v1/auth/csrf')
      const detail = await page.request.get(
        'http://localhost:8080/api/v1/companies/' + companyUrl.split('/').pop(),
      )
      if (csrf.ok() && detail.ok())
        await page.request.delete(detail.url(), {
          headers: {
            Origin: 'http://localhost:5173',
            'X-CSRF-Token': (await csrf.json()).csrf_token,
            'If-Match': detail.headers().etag,
          },
        })
    }
  }
})
